- name: Debug Secrets
  run: |
    echo "FTP Server Address: ${{ secrets.FTP_SERVER_ADDRESS }}"
    echo "FTP Username: ${{ secrets.FTP_USERNAME }}"
    echo "FTP Password: ${{ secrets.FTP_PASSWORD }}"
    echo "FTP Port: ${{ secrets.FTP_PORT }}"
